language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.1"
  - "iojs"
after_script: npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ab204e5cf80192468dd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
