language: node_js
node_js:
  - "6"
# node_js 4+ requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8"
# gcc 4.8 requires ubuntu-toolchain-r-test
sudo: required
services:
  - docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
before_install:
  # setup xvfb for browser based tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
script:
  - npm run test:ci
#after_script: npm run coveralls
#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/0ab204e5cf80192468dd
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
