language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
# node_js 4+ requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8"
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
after_script: npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ab204e5cf80192468dd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
